
// This file has been generated by the GUI designer. Do not modify.
namespace Mono.Instrumentation.Monitor
{
	internal partial class InstrumenationChartView
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox;

		private global::Gtk.Label labelTitle;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonSaveAs;

		private global::Gtk.Button buttonDelete;

		private global::Gtk.HPaned hpaned2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox boxCharts;

		private global::Gtk.HBox hboxChartBar;

		private global::Gtk.ToggleButton toggleTimeView;

		private global::Gtk.ToggleButton toggleListView;

		private global::Gtk.Button buttonFlush;

		private global::Gtk.Button buttonZoomOut;

		private global::Gtk.Button buttonZoomIn;

		private global::Gtk.VBox frameCharts;

		private global::Gtk.HScrollbar chartScroller;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hboxSeriesBar;

		private global::Gtk.Button buttonRemoveCounter;

		private global::Gtk.Button buttonAddCounter;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView listSeries;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Mono.Instrumentation.Monitor.InstrumenationChartView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Mono.Instrumentation.Monitor.InstrumenationChartView";
			// Container child Mono.Instrumentation.Monitor.InstrumenationChartView.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			// Container child hbox.Gtk.Box+BoxChild
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.Xalign = 0f;
			this.hbox.Add (this.labelTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox[this.labelTitle]));
			w1.Position = 0;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			// Container child buttonSave.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Button);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w3.Add (w6);
			w2.Add (w3);
			this.buttonSave.Add (w2);
			this.hbox.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox[this.buttonSave]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonSaveAs = new global::Gtk.Button ();
			this.buttonSaveAs.CanFocus = true;
			this.buttonSaveAs.Name = "buttonSaveAs";
			this.buttonSaveAs.UseUnderline = true;
			// Container child buttonSaveAs.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Button);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w12.Add (w15);
			w11.Add (w12);
			this.buttonSaveAs.Add (w11);
			this.hbox.Add (this.buttonSaveAs);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox[this.buttonSaveAs]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			// Container child buttonDelete.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Button);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w21.Add (w24);
			w20.Add (w21);
			this.buttonDelete.Add (w20);
			this.hbox.Add (this.buttonDelete);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox[this.buttonDelete]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox3.Add (this.hbox);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 471;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.boxCharts = new global::Gtk.VBox ();
			this.boxCharts.Name = "boxCharts";
			this.boxCharts.Spacing = 6;
			// Container child boxCharts.Gtk.Box+BoxChild
			this.hboxChartBar = new global::Gtk.HBox ();
			this.hboxChartBar.Name = "hboxChartBar";
			this.hboxChartBar.Spacing = 6;
			// Container child hboxChartBar.Gtk.Box+BoxChild
			this.toggleTimeView = new global::Gtk.ToggleButton ();
			this.toggleTimeView.CanFocus = true;
			this.toggleTimeView.Name = "toggleTimeView";
			this.toggleTimeView.UseUnderline = true;
			this.toggleTimeView.Label = global::Mono.Unix.Catalog.GetString ("Time View");
			this.hboxChartBar.Add (this.toggleTimeView);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxChartBar[this.toggleTimeView]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hboxChartBar.Gtk.Box+BoxChild
			this.toggleListView = new global::Gtk.ToggleButton ();
			this.toggleListView.CanFocus = true;
			this.toggleListView.Name = "toggleListView";
			this.toggleListView.UseUnderline = true;
			this.toggleListView.Label = global::Mono.Unix.Catalog.GetString ("List View");
			this.hboxChartBar.Add (this.toggleListView);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hboxChartBar[this.toggleListView]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hboxChartBar.Gtk.Box+BoxChild
			this.buttonFlush = new global::Gtk.Button ();
			this.buttonFlush.CanFocus = true;
			this.buttonFlush.Name = "buttonFlush";
			this.buttonFlush.UseUnderline = true;
			this.buttonFlush.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonFlush.Label = global::Mono.Unix.Catalog.GetString ("Flush Memory");
			this.hboxChartBar.Add (this.buttonFlush);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hboxChartBar[this.buttonFlush]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hboxChartBar.Gtk.Box+BoxChild
			this.buttonZoomOut = new global::Gtk.Button ();
			this.buttonZoomOut.CanFocus = true;
			this.buttonZoomOut.Name = "buttonZoomOut";
			this.buttonZoomOut.UseUnderline = true;
			// Container child buttonZoomOut.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-out", global::Gtk.IconSize.Menu);
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w34.Add (w37);
			w33.Add (w34);
			this.buttonZoomOut.Add (w33);
			this.hboxChartBar.Add (this.buttonZoomOut);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hboxChartBar[this.buttonZoomOut]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 3;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hboxChartBar.Gtk.Box+BoxChild
			this.buttonZoomIn = new global::Gtk.Button ();
			this.buttonZoomIn.CanFocus = true;
			this.buttonZoomIn.Name = "buttonZoomIn";
			this.buttonZoomIn.UseUnderline = true;
			// Container child buttonZoomIn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-in", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w43.Add (w46);
			w42.Add (w43);
			this.buttonZoomIn.Add (w42);
			this.hboxChartBar.Add (this.buttonZoomIn);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hboxChartBar[this.buttonZoomIn]));
			w50.PackType = ((global::Gtk.PackType)(1));
			w50.Position = 4;
			w50.Expand = false;
			w50.Fill = false;
			this.boxCharts.Add (this.hboxChartBar);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.boxCharts[this.hboxChartBar]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child boxCharts.Gtk.Box+BoxChild
			this.frameCharts = new global::Gtk.VBox ();
			this.frameCharts.Name = "frameCharts";
			this.frameCharts.Spacing = 6;
			// Container child frameCharts.Gtk.Box+BoxChild
			this.chartScroller = new global::Gtk.HScrollbar (null);
			this.chartScroller.Name = "chartScroller";
			this.chartScroller.Adjustment.Upper = 100;
			this.chartScroller.Adjustment.PageIncrement = 10;
			this.chartScroller.Adjustment.PageSize = 10;
			this.chartScroller.Adjustment.StepIncrement = 1;
			this.frameCharts.Add (this.chartScroller);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.frameCharts[this.chartScroller]));
			w52.PackType = ((global::Gtk.PackType)(1));
			w52.Position = 2;
			w52.Expand = false;
			w52.Fill = false;
			this.boxCharts.Add (this.frameCharts);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.boxCharts[this.frameCharts]));
			w53.Position = 1;
			this.hbox4.Add (this.boxCharts);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.boxCharts]));
			w54.Position = 0;
			this.hpaned2.Add (this.hbox4);
			global::Gtk.Paned.PanedChild w55 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.hbox4]));
			w55.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hboxSeriesBar = new global::Gtk.HBox ();
			this.hboxSeriesBar.Name = "hboxSeriesBar";
			this.hboxSeriesBar.Spacing = 6;
			// Container child hboxSeriesBar.Gtk.Box+BoxChild
			this.buttonRemoveCounter = new global::Gtk.Button ();
			this.buttonRemoveCounter.CanFocus = true;
			this.buttonRemoveCounter.Name = "buttonRemoveCounter";
			this.buttonRemoveCounter.UseStock = true;
			this.buttonRemoveCounter.UseUnderline = true;
			this.buttonRemoveCounter.Label = "gtk-remove";
			this.hboxSeriesBar.Add (this.buttonRemoveCounter);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hboxSeriesBar[this.buttonRemoveCounter]));
			w56.PackType = ((global::Gtk.PackType)(1));
			w56.Position = 0;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hboxSeriesBar.Gtk.Box+BoxChild
			this.buttonAddCounter = new global::Gtk.Button ();
			this.buttonAddCounter.CanFocus = true;
			this.buttonAddCounter.Name = "buttonAddCounter";
			this.buttonAddCounter.UseStock = true;
			this.buttonAddCounter.UseUnderline = true;
			this.buttonAddCounter.Label = "gtk-add";
			this.hboxSeriesBar.Add (this.buttonAddCounter);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hboxSeriesBar[this.buttonAddCounter]));
			w57.PackType = ((global::Gtk.PackType)(1));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.vbox5.Add (this.hboxSeriesBar);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hboxSeriesBar]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.listSeries = new global::Gtk.TreeView ();
			this.listSeries.WidthRequest = 100;
			this.listSeries.CanFocus = true;
			this.listSeries.Name = "listSeries";
			this.listSeries.HeadersVisible = false;
			this.GtkScrolledWindow1.Add (this.listSeries);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow1]));
			w60.Position = 1;
			this.hpaned2.Add (this.vbox5);
			global::Gtk.Paned.PanedChild w61 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.vbox5]));
			w61.Resize = false;
			w61.Shrink = false;
			this.vbox3.Add (this.hpaned2);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hpaned2]));
			w62.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonSaveAs.Clicked += new global::System.EventHandler (this.OnButtonSaveAsClicked);
			this.buttonDelete.Clicked += new global::System.EventHandler (this.OnButtonDeleteClicked);
			this.toggleTimeView.Toggled += new global::System.EventHandler (this.OnToggleTimeViewToggled);
			this.toggleListView.Toggled += new global::System.EventHandler (this.OnToggleListViewToggled);
			this.buttonFlush.Clicked += new global::System.EventHandler (this.OnButtonFlushClicked);
			this.buttonZoomIn.Clicked += new global::System.EventHandler (this.OnButtonZoomInClicked);
			this.buttonZoomOut.Clicked += new global::System.EventHandler (this.OnButtonZoomOutClicked);
			this.chartScroller.ValueChanged += new global::System.EventHandler (this.OnChartScrollerValueChanged);
			this.buttonAddCounter.Clicked += new global::System.EventHandler (this.OnButtonAddCounterClicked);
			this.buttonRemoveCounter.Clicked += new global::System.EventHandler (this.OnButtonRemoveCounterClicked);
		}
	}
}
