//
//  Copyright (c) Microsoft Corporation. All rights reserved.
//  Licensed under the MIT License. See License.txt in the project root for license information.
//
// This file contain implementations details that are subject to change without notice.
// Use at your own risk.
//
#if CODE_ANALYSIS_BASELINE
using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Performance","CA1822:MarkMembersAsStatic", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.EditorPrimitivesFactoryService.#GetBufferPrimitives(Microsoft.VisualStudio.Text.ITextBuffer)")]
[module: SuppressMessage("Microsoft.Usage","CA1801:ReviewUnusedParameters", MessageId="textBuffer", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.EditorPrimitivesFactoryService.#GetBufferPrimitives(Microsoft.VisualStudio.Text.ITextBuffer)")]
[module: SuppressMessage("Microsoft.Performance","CA1812:AvoidUninstantiatedInternalClasses", Scope="type", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService", Justification="Component model instantiates these classes")]
[module: SuppressMessage("Microsoft.Performance","CA1812:AvoidUninstantiatedInternalClasses", Scope="type", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService", Justification="Component model instantiates these classes")]
[module: SuppressMessage("Microsoft.Performance","CA1812:AvoidUninstantiatedInternalClasses", Scope="type", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService", Justification="Component model instantiates these classes")]
[module: SuppressMessage("Microsoft.Performance","CA1812:AvoidUninstantiatedInternalClasses", Scope="type", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService", Justification="Component model instantiates these classes")]

//ToDo: To be looked at
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService.#CreateTextBuffer(Microsoft.VisualStudio.Text.ITextBuffer)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService.#CreateTextPoint(Microsoft.VisualStudio.Text.Editor.TextBuffer,System.Int32)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultDisplayTextPointPrimitive.#GetDisplayTextRange(Microsoft.VisualStudio.Text.Editor.DisplayTextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultDisplayTextRangePrimitive.#MoveTo(Microsoft.VisualStudio.Text.Editor.TextRange)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#ExtendSelection(Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#ReplaceText(System.String)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#SelectRange(Microsoft.VisualStudio.Text.Editor.TextPoint,Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="1", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#SelectRange(Microsoft.VisualStudio.Text.Editor.TextPoint,Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#SelectRange(Microsoft.VisualStudio.Text.Editor.TextRange)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultSelectionPrimitive.#SetStart(Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextPointPrimitive.#FindAll(System.String,Microsoft.VisualStudio.Text.Operations.FindOptions)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="2", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextPointPrimitive.#FindAll(System.String,Microsoft.VisualStudio.Text.Operations.FindOptions,Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextRangePrimitive.#MoveTo(Microsoft.VisualStudio.Text.Editor.TextRange)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextRangePrimitive.#SetEnd(Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextRangePrimitive.#SetStart(Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextViewPrimitive.#GetTextPoint(Microsoft.VisualStudio.Text.Editor.TextPoint)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextViewPrimitive.#Show(Microsoft.VisualStudio.Text.Editor.DisplayTextPoint,Microsoft.VisualStudio.Text.Editor.HowToShow)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultTextViewPrimitive.#Show(Microsoft.VisualStudio.Text.Editor.DisplayTextRange,Microsoft.VisualStudio.Text.Editor.HowToShow)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#CreateCaret(Microsoft.VisualStudio.Text.Editor.TextView)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#CreateDisplayTextPoint(Microsoft.VisualStudio.Text.Editor.TextView,System.Int32)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#CreateSelection(Microsoft.VisualStudio.Text.Editor.TextView)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#CreateTextView(Microsoft.VisualStudio.Text.Editor.ITextView)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService.#set_EditorOptionsFactoryService(Microsoft.VisualStudio.Text.Editor.IEditorOptionsFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService.#set_TextSearchService(Microsoft.VisualStudio.Text.Operations.ITextSearchService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultBufferPrimitivesFactoryService.#set_TextStructureNavigatorSelectorService(Microsoft.VisualStudio.Text.Operations.ITextStructureNavigatorSelectorService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#set_BufferPrimitivesFactoryService(Microsoft.VisualStudio.Text.Editor.IBufferPrimitivesFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.DefaultViewPrimitivesFactoryService.#set_EditorOptionsFactoryService(Microsoft.VisualStudio.Text.Editor.IEditorOptionsFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.EditorPrimitivesFactoryService.#set_BufferPrimitivesFactory(Microsoft.VisualStudio.Text.Editor.IBufferPrimitivesFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.EditorPrimitives.Implementation.EditorPrimitivesFactoryService.#set_ViewPrimitivesFactory(Microsoft.VisualStudio.Text.Editor.IViewPrimitivesFactoryService)", Justification="ToDo: To be looked at")]

#endif