// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.Autotools {
    
    
    public partial class MakefileOptionPanelWidget {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.CheckButton cbEnableMakefileIntegration;
        
        private Gtk.HSeparator headerSep1;
        
        private Gtk.Table table1;
        
        private MonoDevelop.Components.FileEntry fileEntryMakefilePath;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ComboBox comboAssemblyName;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ComboBox comboOutputDir;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Entry BuildTargetName;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Entry CleanTargetName;
        
        private Gtk.HSeparator headerSep2;
        
        private Gtk.Label lblAssemblyNameVar;
        
        private Gtk.Label lblBuildTargetName;
        
        private Gtk.Label lblCleanTargetName;
        
        private Gtk.Label lblMakefileName;
        
        private Gtk.Label lblOutputDirVar;
        
        private Gtk.Label label1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.CheckButton cbFileSync;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Table table3;
        
        private Gtk.CheckButton cbKeepDeployFilesSync;
        
        private Gtk.CheckButton cbKeepFilesSync;
        
        private Gtk.CheckButton cbKeepOthersSync;
        
        private Gtk.CheckButton cbKeepResourcesSync;
        
        private Gtk.ComboBox comboDeployFilesVar;
        
        private Gtk.ComboBox comboFilesVar;
        
        private Gtk.ComboBox comboOthersVar;
        
        private Gtk.ComboBox comboResourcesVar;
        
        private Gtk.Entry entryDeployFilesPattern;
        
        private Gtk.Entry entryFilesPattern;
        
        private Gtk.Entry entryResourcesPattern;
        
        private Gtk.EventBox eventbox1;
        
        private Gtk.Entry entryOthersPattern;
        
        private Gtk.Label label5;
        
        private Gtk.Label lblCol2;
        
        private Gtk.Label lblCol3;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox4;
        
        private Gtk.CheckButton cbKeepRefSync;
        
        private Gtk.HSeparator hseparator5;
        
        private Gtk.Table table4;
        
        private Gtk.CheckButton cbAutotoolsProject;
        
        private Gtk.ComboBox comboAsmRefVar;
        
        private Gtk.ComboBox comboGacRefVar;
        
        private Gtk.ComboBox comboProjectRefVar;
        
        private Gtk.Entry entryAsmRefPattern;
        
        private Gtk.Entry entryGacRefPattern;
        
        private Gtk.Entry entryProjectRefPattern;
        
        private MonoDevelop.Components.FolderEntry fileEntryConfigureInPath;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Label label6;
        
        private Gtk.Label lblAsmRef;
        
        private Gtk.Label lblCol5;
        
        private Gtk.Label lblCol6;
        
        private Gtk.Label lblConfigureInPath;
        
        private Gtk.Label lblGacRef;
        
        private Gtk.Label lblProjectRef;
        
        private Gtk.Label label3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoDevelop.Autotools.MakefileOptionPanelWidget
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "MonoDevelop.Autotools.MakefileOptionPanelWidget";
            // Container child MonoDevelop.Autotools.MakefileOptionPanelWidget.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(6));
            // Container child vbox1.Gtk.Box+BoxChild
            this.cbEnableMakefileIntegration = new Gtk.CheckButton();
            this.cbEnableMakefileIntegration.CanFocus = true;
            this.cbEnableMakefileIntegration.Name = "cbEnableMakefileIntegration";
            this.cbEnableMakefileIntegration.Label = Mono.Unix.Catalog.GetString("Enable makefile Integration in this project");
            this.cbEnableMakefileIntegration.DrawIndicator = true;
            this.vbox1.Add(this.cbEnableMakefileIntegration);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.cbEnableMakefileIntegration]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.headerSep1 = new Gtk.HSeparator();
            this.headerSep1.Name = "headerSep1";
            this.vbox1.Add(this.headerSep1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.headerSep1]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.fileEntryMakefilePath = new MonoDevelop.Components.FileEntry();
            this.fileEntryMakefilePath.Name = "fileEntryMakefilePath";
            this.fileEntryMakefilePath.BrowserTitle = "";
            this.table1.Add(this.fileEntryMakefilePath);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.fileEntryMakefilePath]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.comboAssemblyName = Gtk.ComboBox.NewText();
            this.comboAssemblyName.WidthRequest = 300;
            this.comboAssemblyName.Name = "comboAssemblyName";
            this.hbox1.Add(this.comboAssemblyName);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.comboAssemblyName]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w5.TopAttach = ((uint)(4));
            w5.BottomAttach = ((uint)(5));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            // Container child hbox2.Gtk.Box+BoxChild
            this.comboOutputDir = Gtk.ComboBox.NewText();
            this.comboOutputDir.WidthRequest = 300;
            this.comboOutputDir.Name = "comboOutputDir";
            this.hbox2.Add(this.comboOutputDir);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.comboOutputDir]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            this.table1.Add(this.hbox2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.hbox2]));
            w7.TopAttach = ((uint)(5));
            w7.BottomAttach = ((uint)(6));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            // Container child hbox3.Gtk.Box+BoxChild
            this.BuildTargetName = new Gtk.Entry();
            this.BuildTargetName.WidthRequest = 200;
            this.BuildTargetName.CanFocus = true;
            this.BuildTargetName.Name = "BuildTargetName";
            this.BuildTargetName.IsEditable = true;
            this.BuildTargetName.InvisibleChar = '●';
            this.hbox3.Add(this.BuildTargetName);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.BuildTargetName]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            this.table1.Add(this.hbox3);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.hbox3]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            // Container child hbox4.Gtk.Box+BoxChild
            this.CleanTargetName = new Gtk.Entry();
            this.CleanTargetName.WidthRequest = 200;
            this.CleanTargetName.CanFocus = true;
            this.CleanTargetName.Name = "CleanTargetName";
            this.CleanTargetName.IsEditable = true;
            this.CleanTargetName.InvisibleChar = '●';
            this.hbox4.Add(this.CleanTargetName);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox4[this.CleanTargetName]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            this.table1.Add(this.hbox4);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.hbox4]));
            w11.TopAttach = ((uint)(3));
            w11.BottomAttach = ((uint)(4));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.headerSep2 = new Gtk.HSeparator();
            this.headerSep2.Name = "headerSep2";
            this.table1.Add(this.headerSep2);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.headerSep2]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblAssemblyNameVar = new Gtk.Label();
            this.lblAssemblyNameVar.Name = "lblAssemblyNameVar";
            this.lblAssemblyNameVar.Xalign = 0F;
            this.lblAssemblyNameVar.LabelProp = Mono.Unix.Catalog.GetString("Assembly Name variable:");
            this.table1.Add(this.lblAssemblyNameVar);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.lblAssemblyNameVar]));
            w13.TopAttach = ((uint)(4));
            w13.BottomAttach = ((uint)(5));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblBuildTargetName = new Gtk.Label();
            this.lblBuildTargetName.Name = "lblBuildTargetName";
            this.lblBuildTargetName.Xalign = 0F;
            this.lblBuildTargetName.LabelProp = Mono.Unix.Catalog.GetString("Build target name:");
            this.table1.Add(this.lblBuildTargetName);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.lblBuildTargetName]));
            w14.TopAttach = ((uint)(2));
            w14.BottomAttach = ((uint)(3));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblCleanTargetName = new Gtk.Label();
            this.lblCleanTargetName.Name = "lblCleanTargetName";
            this.lblCleanTargetName.Xalign = 0F;
            this.lblCleanTargetName.LabelProp = Mono.Unix.Catalog.GetString("Clean target name:");
            this.table1.Add(this.lblCleanTargetName);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.lblCleanTargetName]));
            w15.TopAttach = ((uint)(3));
            w15.BottomAttach = ((uint)(4));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblMakefileName = new Gtk.Label();
            this.lblMakefileName.Name = "lblMakefileName";
            this.lblMakefileName.Xalign = 0F;
            this.lblMakefileName.LabelProp = Mono.Unix.Catalog.GetString("Makefile path:");
            this.table1.Add(this.lblMakefileName);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.lblMakefileName]));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblOutputDirVar = new Gtk.Label();
            this.lblOutputDirVar.Name = "lblOutputDirVar";
            this.lblOutputDirVar.Xalign = 0F;
            this.lblOutputDirVar.LabelProp = Mono.Unix.Catalog.GetString("Output directory variable:");
            this.table1.Add(this.lblOutputDirVar);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.lblOutputDirVar]));
            w17.TopAttach = ((uint)(5));
            w17.BottomAttach = ((uint)(6));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w18.Position = 2;
            w18.Expand = false;
            w18.Fill = false;
            this.notebook1.Add(this.vbox1);
            Gtk.Notebook.NotebookChild w19 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox1]));
            w19.TabExpand = false;
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Makefile");
            this.notebook1.SetTabLabel(this.vbox1, this.label1);
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.cbFileSync = new Gtk.CheckButton();
            this.cbFileSync.CanFocus = true;
            this.cbFileSync.Name = "cbFileSync";
            this.cbFileSync.Label = Mono.Unix.Catalog.GetString("Enable project file synchronization");
            this.cbFileSync.DrawIndicator = true;
            this.cbFileSync.UseUnderline = true;
            this.vbox2.Add(this.cbFileSync);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox2[this.cbFileSync]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox2.Add(this.hseparator2);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(6)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.cbKeepDeployFilesSync = new Gtk.CheckButton();
            this.cbKeepDeployFilesSync.CanFocus = true;
            this.cbKeepDeployFilesSync.Name = "cbKeepDeployFilesSync";
            this.cbKeepDeployFilesSync.Label = Mono.Unix.Catalog.GetString("Deployment files");
            this.cbKeepDeployFilesSync.DrawIndicator = true;
            this.table3.Add(this.cbKeepDeployFilesSync);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table3[this.cbKeepDeployFilesSync]));
            w22.TopAttach = ((uint)(4));
            w22.BottomAttach = ((uint)(5));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbKeepFilesSync = new Gtk.CheckButton();
            this.cbKeepFilesSync.CanFocus = true;
            this.cbKeepFilesSync.Name = "cbKeepFilesSync";
            this.cbKeepFilesSync.Label = Mono.Unix.Catalog.GetString("Source code files");
            this.cbKeepFilesSync.DrawIndicator = true;
            this.table3.Add(this.cbKeepFilesSync);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table3[this.cbKeepFilesSync]));
            w23.TopAttach = ((uint)(2));
            w23.BottomAttach = ((uint)(3));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbKeepOthersSync = new Gtk.CheckButton();
            this.cbKeepOthersSync.CanFocus = true;
            this.cbKeepOthersSync.Name = "cbKeepOthersSync";
            this.cbKeepOthersSync.Label = Mono.Unix.Catalog.GetString("Other Files");
            this.cbKeepOthersSync.DrawIndicator = true;
            this.table3.Add(this.cbKeepOthersSync);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table3[this.cbKeepOthersSync]));
            w24.TopAttach = ((uint)(5));
            w24.BottomAttach = ((uint)(6));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbKeepResourcesSync = new Gtk.CheckButton();
            this.cbKeepResourcesSync.CanFocus = true;
            this.cbKeepResourcesSync.Name = "cbKeepResourcesSync";
            this.cbKeepResourcesSync.Label = Mono.Unix.Catalog.GetString("Resources");
            this.cbKeepResourcesSync.DrawIndicator = true;
            this.table3.Add(this.cbKeepResourcesSync);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table3[this.cbKeepResourcesSync]));
            w25.TopAttach = ((uint)(3));
            w25.BottomAttach = ((uint)(4));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.comboDeployFilesVar = Gtk.ComboBox.NewText();
            this.comboDeployFilesVar.WidthRequest = 200;
            this.comboDeployFilesVar.Name = "comboDeployFilesVar";
            this.table3.Add(this.comboDeployFilesVar);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table3[this.comboDeployFilesVar]));
            w26.TopAttach = ((uint)(4));
            w26.BottomAttach = ((uint)(5));
            w26.LeftAttach = ((uint)(1));
            w26.RightAttach = ((uint)(2));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.comboFilesVar = Gtk.ComboBox.NewText();
            this.comboFilesVar.WidthRequest = 200;
            this.comboFilesVar.Name = "comboFilesVar";
            this.comboFilesVar.Active = 0;
            this.table3.Add(this.comboFilesVar);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table3[this.comboFilesVar]));
            w27.TopAttach = ((uint)(2));
            w27.BottomAttach = ((uint)(3));
            w27.LeftAttach = ((uint)(1));
            w27.RightAttach = ((uint)(2));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.comboOthersVar = Gtk.ComboBox.NewText();
            this.comboOthersVar.WidthRequest = 200;
            this.comboOthersVar.Name = "comboOthersVar";
            this.table3.Add(this.comboOthersVar);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table3[this.comboOthersVar]));
            w28.TopAttach = ((uint)(5));
            w28.BottomAttach = ((uint)(6));
            w28.LeftAttach = ((uint)(1));
            w28.RightAttach = ((uint)(2));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.comboResourcesVar = Gtk.ComboBox.NewText();
            this.comboResourcesVar.WidthRequest = 200;
            this.comboResourcesVar.Name = "comboResourcesVar";
            this.table3.Add(this.comboResourcesVar);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table3[this.comboResourcesVar]));
            w29.TopAttach = ((uint)(3));
            w29.BottomAttach = ((uint)(4));
            w29.LeftAttach = ((uint)(1));
            w29.RightAttach = ((uint)(2));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.entryDeployFilesPattern = new Gtk.Entry();
            this.entryDeployFilesPattern.CanFocus = true;
            this.entryDeployFilesPattern.Name = "entryDeployFilesPattern";
            this.entryDeployFilesPattern.IsEditable = true;
            this.entryDeployFilesPattern.InvisibleChar = '●';
            this.table3.Add(this.entryDeployFilesPattern);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table3[this.entryDeployFilesPattern]));
            w30.TopAttach = ((uint)(4));
            w30.BottomAttach = ((uint)(5));
            w30.LeftAttach = ((uint)(2));
            w30.RightAttach = ((uint)(3));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.entryFilesPattern = new Gtk.Entry();
            this.entryFilesPattern.CanFocus = true;
            this.entryFilesPattern.Name = "entryFilesPattern";
            this.entryFilesPattern.IsEditable = true;
            this.entryFilesPattern.InvisibleChar = '●';
            this.table3.Add(this.entryFilesPattern);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table3[this.entryFilesPattern]));
            w31.TopAttach = ((uint)(2));
            w31.BottomAttach = ((uint)(3));
            w31.LeftAttach = ((uint)(2));
            w31.RightAttach = ((uint)(3));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.entryResourcesPattern = new Gtk.Entry();
            this.entryResourcesPattern.CanFocus = true;
            this.entryResourcesPattern.Name = "entryResourcesPattern";
            this.entryResourcesPattern.IsEditable = true;
            this.entryResourcesPattern.InvisibleChar = '●';
            this.table3.Add(this.entryResourcesPattern);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table3[this.entryResourcesPattern]));
            w32.TopAttach = ((uint)(3));
            w32.BottomAttach = ((uint)(4));
            w32.LeftAttach = ((uint)(2));
            w32.RightAttach = ((uint)(3));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.eventbox1 = new Gtk.EventBox();
            this.eventbox1.Name = "eventbox1";
            // Container child eventbox1.Gtk.Container+ContainerChild
            this.entryOthersPattern = new Gtk.Entry();
            this.entryOthersPattern.CanFocus = true;
            this.entryOthersPattern.Name = "entryOthersPattern";
            this.entryOthersPattern.IsEditable = true;
            this.entryOthersPattern.InvisibleChar = '●';
            this.eventbox1.Add(this.entryOthersPattern);
            this.table3.Add(this.eventbox1);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table3[this.eventbox1]));
            w34.TopAttach = ((uint)(5));
            w34.BottomAttach = ((uint)(6));
            w34.LeftAttach = ((uint)(2));
            w34.RightAttach = ((uint)(3));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.WidthRequest = 500;
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Select the kind of files you want to synchronize with the makefile. For each file kind please specify the makefile variable that holds the list and optionally a prefix to be prepended to each file name.");
            this.label5.Wrap = true;
            this.table3.Add(this.label5);
            Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table3[this.label5]));
            w35.RightAttach = ((uint)(3));
            w35.YPadding = ((uint)(9));
            w35.XOptions = ((Gtk.AttachOptions)(4));
            w35.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.lblCol2 = new Gtk.Label();
            this.lblCol2.Name = "lblCol2";
            this.lblCol2.Xalign = 0F;
            this.lblCol2.LabelProp = Mono.Unix.Catalog.GetString("Makefile variable name:");
            this.table3.Add(this.lblCol2);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table3[this.lblCol2]));
            w36.TopAttach = ((uint)(1));
            w36.BottomAttach = ((uint)(2));
            w36.LeftAttach = ((uint)(1));
            w36.RightAttach = ((uint)(2));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.lblCol3 = new Gtk.Label();
            this.lblCol3.Name = "lblCol3";
            this.lblCol3.Xalign = 0F;
            this.lblCol3.LabelProp = Mono.Unix.Catalog.GetString("Prefix:");
            this.table3.Add(this.lblCol3);
            Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table3[this.lblCol3]));
            w37.TopAttach = ((uint)(1));
            w37.BottomAttach = ((uint)(2));
            w37.LeftAttach = ((uint)(2));
            w37.RightAttach = ((uint)(3));
            w37.XOptions = ((Gtk.AttachOptions)(4));
            w37.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table3);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox2[this.table3]));
            w38.Position = 2;
            w38.Expand = false;
            w38.Fill = false;
            this.notebook1.Add(this.vbox2);
            Gtk.Notebook.NotebookChild w39 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
            w39.Position = 1;
            w39.TabExpand = false;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Files");
            this.notebook1.SetTabLabel(this.vbox2, this.label2);
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            this.vbox4.BorderWidth = ((uint)(6));
            // Container child vbox4.Gtk.Box+BoxChild
            this.cbKeepRefSync = new Gtk.CheckButton();
            this.cbKeepRefSync.CanFocus = true;
            this.cbKeepRefSync.Name = "cbKeepRefSync";
            this.cbKeepRefSync.Label = Mono.Unix.Catalog.GetString("Enable references synchronization");
            this.cbKeepRefSync.DrawIndicator = true;
            this.vbox4.Add(this.cbKeepRefSync);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox4[this.cbKeepRefSync]));
            w40.Position = 0;
            w40.Expand = false;
            w40.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hseparator5 = new Gtk.HSeparator();
            this.hseparator5.Name = "hseparator5";
            this.vbox4.Add(this.hseparator5);
            Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox4[this.hseparator5]));
            w41.Position = 1;
            w41.Expand = false;
            w41.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.table4 = new Gtk.Table(((uint)(8)), ((uint)(3)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.cbAutotoolsProject = new Gtk.CheckButton();
            this.cbAutotoolsProject.CanFocus = true;
            this.cbAutotoolsProject.Name = "cbAutotoolsProject";
            this.cbAutotoolsProject.Label = Mono.Unix.Catalog.GetString("Look for packages in configure.in");
            this.cbAutotoolsProject.DrawIndicator = true;
            this.table4.Add(this.cbAutotoolsProject);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table4[this.cbAutotoolsProject]));
            w42.TopAttach = ((uint)(6));
            w42.BottomAttach = ((uint)(7));
            w42.RightAttach = ((uint)(3));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.comboAsmRefVar = Gtk.ComboBox.NewText();
            this.comboAsmRefVar.WidthRequest = 200;
            this.comboAsmRefVar.Name = "comboAsmRefVar";
            this.table4.Add(this.comboAsmRefVar);
            Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table4[this.comboAsmRefVar]));
            w43.TopAttach = ((uint)(3));
            w43.BottomAttach = ((uint)(4));
            w43.LeftAttach = ((uint)(1));
            w43.RightAttach = ((uint)(2));
            w43.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.comboGacRefVar = Gtk.ComboBox.NewText();
            this.comboGacRefVar.WidthRequest = 200;
            this.comboGacRefVar.Name = "comboGacRefVar";
            this.table4.Add(this.comboGacRefVar);
            Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table4[this.comboGacRefVar]));
            w44.TopAttach = ((uint)(2));
            w44.BottomAttach = ((uint)(3));
            w44.LeftAttach = ((uint)(1));
            w44.RightAttach = ((uint)(2));
            w44.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.comboProjectRefVar = Gtk.ComboBox.NewText();
            this.comboProjectRefVar.WidthRequest = 200;
            this.comboProjectRefVar.Name = "comboProjectRefVar";
            this.table4.Add(this.comboProjectRefVar);
            Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table4[this.comboProjectRefVar]));
            w45.TopAttach = ((uint)(4));
            w45.BottomAttach = ((uint)(5));
            w45.LeftAttach = ((uint)(1));
            w45.RightAttach = ((uint)(2));
            w45.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryAsmRefPattern = new Gtk.Entry();
            this.entryAsmRefPattern.CanFocus = true;
            this.entryAsmRefPattern.Name = "entryAsmRefPattern";
            this.entryAsmRefPattern.IsEditable = true;
            this.entryAsmRefPattern.InvisibleChar = '●';
            this.table4.Add(this.entryAsmRefPattern);
            Gtk.Table.TableChild w46 = ((Gtk.Table.TableChild)(this.table4[this.entryAsmRefPattern]));
            w46.TopAttach = ((uint)(3));
            w46.BottomAttach = ((uint)(4));
            w46.LeftAttach = ((uint)(2));
            w46.RightAttach = ((uint)(3));
            w46.XOptions = ((Gtk.AttachOptions)(4));
            w46.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryGacRefPattern = new Gtk.Entry();
            this.entryGacRefPattern.CanFocus = true;
            this.entryGacRefPattern.Name = "entryGacRefPattern";
            this.entryGacRefPattern.IsEditable = true;
            this.entryGacRefPattern.InvisibleChar = '●';
            this.table4.Add(this.entryGacRefPattern);
            Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.table4[this.entryGacRefPattern]));
            w47.TopAttach = ((uint)(2));
            w47.BottomAttach = ((uint)(3));
            w47.LeftAttach = ((uint)(2));
            w47.RightAttach = ((uint)(3));
            w47.XOptions = ((Gtk.AttachOptions)(4));
            w47.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryProjectRefPattern = new Gtk.Entry();
            this.entryProjectRefPattern.CanFocus = true;
            this.entryProjectRefPattern.Name = "entryProjectRefPattern";
            this.entryProjectRefPattern.IsEditable = true;
            this.entryProjectRefPattern.InvisibleChar = '●';
            this.table4.Add(this.entryProjectRefPattern);
            Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.table4[this.entryProjectRefPattern]));
            w48.TopAttach = ((uint)(4));
            w48.BottomAttach = ((uint)(5));
            w48.LeftAttach = ((uint)(2));
            w48.RightAttach = ((uint)(3));
            w48.XOptions = ((Gtk.AttachOptions)(4));
            w48.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.fileEntryConfigureInPath = new MonoDevelop.Components.FolderEntry();
            this.fileEntryConfigureInPath.Name = "fileEntryConfigureInPath";
            this.table4.Add(this.fileEntryConfigureInPath);
            Gtk.Table.TableChild w49 = ((Gtk.Table.TableChild)(this.table4[this.fileEntryConfigureInPath]));
            w49.TopAttach = ((uint)(7));
            w49.BottomAttach = ((uint)(8));
            w49.LeftAttach = ((uint)(1));
            w49.RightAttach = ((uint)(3));
            w49.XOptions = ((Gtk.AttachOptions)(4));
            w49.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.table4.Add(this.hseparator1);
            Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.table4[this.hseparator1]));
            w50.TopAttach = ((uint)(5));
            w50.BottomAttach = ((uint)(6));
            w50.RightAttach = ((uint)(3));
            w50.XOptions = ((Gtk.AttachOptions)(4));
            w50.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.WidthRequest = 500;
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Select the kind of references you want to synchronize with the makefile. For each reference type please specify the makefile variable that holds the list, and optionally a prefix to be prepended to each reference name. You can specify the same variable name for several types of references.");
            this.label6.Wrap = true;
            this.table4.Add(this.label6);
            Gtk.Table.TableChild w51 = ((Gtk.Table.TableChild)(this.table4[this.label6]));
            w51.RightAttach = ((uint)(3));
            w51.YPadding = ((uint)(9));
            w51.XOptions = ((Gtk.AttachOptions)(4));
            w51.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblAsmRef = new Gtk.Label();
            this.lblAsmRef.Name = "lblAsmRef";
            this.lblAsmRef.Xalign = 0F;
            this.lblAsmRef.LabelProp = Mono.Unix.Catalog.GetString("Assembly References");
            this.table4.Add(this.lblAsmRef);
            Gtk.Table.TableChild w52 = ((Gtk.Table.TableChild)(this.table4[this.lblAsmRef]));
            w52.TopAttach = ((uint)(3));
            w52.BottomAttach = ((uint)(4));
            w52.XOptions = ((Gtk.AttachOptions)(4));
            w52.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblCol5 = new Gtk.Label();
            this.lblCol5.Name = "lblCol5";
            this.lblCol5.Xalign = 0F;
            this.lblCol5.LabelProp = Mono.Unix.Catalog.GetString("Makefile variable name:");
            this.table4.Add(this.lblCol5);
            Gtk.Table.TableChild w53 = ((Gtk.Table.TableChild)(this.table4[this.lblCol5]));
            w53.TopAttach = ((uint)(1));
            w53.BottomAttach = ((uint)(2));
            w53.LeftAttach = ((uint)(1));
            w53.RightAttach = ((uint)(2));
            w53.XOptions = ((Gtk.AttachOptions)(4));
            w53.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblCol6 = new Gtk.Label();
            this.lblCol6.Name = "lblCol6";
            this.lblCol6.Xalign = 0F;
            this.lblCol6.LabelProp = Mono.Unix.Catalog.GetString("Prefix:");
            this.table4.Add(this.lblCol6);
            Gtk.Table.TableChild w54 = ((Gtk.Table.TableChild)(this.table4[this.lblCol6]));
            w54.TopAttach = ((uint)(1));
            w54.BottomAttach = ((uint)(2));
            w54.LeftAttach = ((uint)(2));
            w54.RightAttach = ((uint)(3));
            w54.XOptions = ((Gtk.AttachOptions)(4));
            w54.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblConfigureInPath = new Gtk.Label();
            this.lblConfigureInPath.Name = "lblConfigureInPath";
            this.lblConfigureInPath.Xalign = 0F;
            this.lblConfigureInPath.LabelProp = Mono.Unix.Catalog.GetString("Path for configure.in");
            this.table4.Add(this.lblConfigureInPath);
            Gtk.Table.TableChild w55 = ((Gtk.Table.TableChild)(this.table4[this.lblConfigureInPath]));
            w55.TopAttach = ((uint)(7));
            w55.BottomAttach = ((uint)(8));
            w55.XOptions = ((Gtk.AttachOptions)(4));
            w55.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblGacRef = new Gtk.Label();
            this.lblGacRef.Name = "lblGacRef";
            this.lblGacRef.Xalign = 0F;
            this.lblGacRef.LabelProp = Mono.Unix.Catalog.GetString("Package References");
            this.table4.Add(this.lblGacRef);
            Gtk.Table.TableChild w56 = ((Gtk.Table.TableChild)(this.table4[this.lblGacRef]));
            w56.TopAttach = ((uint)(2));
            w56.BottomAttach = ((uint)(3));
            w56.XOptions = ((Gtk.AttachOptions)(4));
            w56.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblProjectRef = new Gtk.Label();
            this.lblProjectRef.Name = "lblProjectRef";
            this.lblProjectRef.Xalign = 0F;
            this.lblProjectRef.LabelProp = Mono.Unix.Catalog.GetString("Project References");
            this.table4.Add(this.lblProjectRef);
            Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table4[this.lblProjectRef]));
            w57.TopAttach = ((uint)(4));
            w57.BottomAttach = ((uint)(5));
            w57.XOptions = ((Gtk.AttachOptions)(4));
            w57.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox4.Add(this.table4);
            Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.vbox4[this.table4]));
            w58.Position = 2;
            w58.Expand = false;
            w58.Fill = false;
            this.notebook1.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w59 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
            w59.Position = 2;
            w59.TabExpand = false;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("References");
            this.notebook1.SetTabLabel(this.vbox4, this.label3);
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.cbEnableMakefileIntegration.Clicked += new System.EventHandler(this.OnEnableMakefileIntegrationClicked);
            this.fileEntryMakefilePath.FocusOutEvent += new Gtk.FocusOutEventHandler(this.OnFileEntryMakefilePathFocusOutEvent);
            this.cbFileSync.Clicked += new System.EventHandler(this.OnCbFileSyncClicked);
            this.cbKeepRefSync.Clicked += new System.EventHandler(this.OnCbKeepRefSyncClicked);
            this.cbAutotoolsProject.Clicked += new System.EventHandler(this.OnCbAutotoolsProjectClicked);
        }
    }
}
