# Makefile for compiling and installing F# MonoDevelop plugin on Mono
#   run 'make' to compile the plugin (dll + debug info)
#   run 'make install' to copy the compiled plugin to MonoDevelop folders
#   run 'make package' to create a deployment binary package with addin (for repository)

# Here are a few paths that need to be configured first:
MDROOT  = INSERT_MD_ROOT
MONOBIN = INSERT_MONO_BIN
FSBIN = INSERT_FSHARP_BIN
MADIR = INSERT_MA_DIR
ATKDIR = INSERT_ATK_DIR
PANGODIR = INSERT_PANGO_DIR
GTKDIR = INSERT_GTK_DIR
GDKDIR = INSERT_GDK_DIR
GLIBDIR = INSERT_GLIB_DIR

MONO = INSERT_MONO
MDTOOL = $(MONO) $(MDROOT)/bin/mdtool.exe 
FSC = INSERT_FSHARP_COMPILER
CSC = INSERT_CSHARP_COMPILER

MDBIN = $(MDROOT)/bin
MDADDIN = $(MDROOT)/AddIns

# Resources and files to be compiled/included as part of the project
RESOURCES = \
	--resource:MonoDevelop.FSharpBinding/FSharpBinding.addin.xml \
	--resource:MonoDevelop.FSharpBinding/templates/EmptyFSharpSource.xft.xml \
	--resource:MonoDevelop.FSharpBinding/templates/EmptyFSharpScript.xft.xml \
	--resource:MonoDevelop.FSharpBinding/templates/FSharpConsoleProject.xpt.xml \
  --resource:MonoDevelop.FSharpBinding/templates/FSharpLibraryProject.xpt.xml \
  --resource:MonoDevelop.FSharpBinding/templates/FSharpTutorialProject.xpt.xml \
	--resource:MonoDevelop.FSharpBinding/templates/FSharpSyntaxMode.xml \
	--resource:MonoDevelop.FSharpBinding/icons/fsharp-icon-32.png \
	--resource:MonoDevelop.FSharpBinding/icons/fsharp-script-32.png \
	--resource:MonoDevelop.FSharpBinding/icons/fsharp-file-icon.png \
	--resource:MonoDevelop.FSharpBinding/icons/fsharp-project-icon.png \
	--resource:MonoDevelop.FSharpBinding/icons/fsharp-script-icon.png

FILES = \
	MonoDevelop.FSharpBinding/PowerPack/CodeDomVisitor.fs \
	MonoDevelop.FSharpBinding/PowerPack/CodeDomGenerator.fs \
	MonoDevelop.FSharpBinding/PowerPack/CodeProvider.fs \
	MonoDevelop.FSharpBinding/PowerPack/LazyList.fsi \
	MonoDevelop.FSharpBinding/PowerPack/LazyList.fs \
	MonoDevelop.FSharpBinding/Services/Mailbox.fs \
	MonoDevelop.FSharpBinding/Services/Parameters.fs \
	MonoDevelop.FSharpBinding/Services/FSharpCompiler.fs \
	MonoDevelop.FSharpBinding/Services/CompilerLocationUtils.fs \
	MonoDevelop.FSharpBinding/Services/Common.fs \
	MonoDevelop.FSharpBinding/Services/Parser.fs \
	MonoDevelop.FSharpBinding/Services/LanguageService.fs \
	MonoDevelop.FSharpBinding/Services/CompilerService.fs \
	MonoDevelop.FSharpBinding/Services/InteractiveSession.fs \
	MonoDevelop.FSharpBinding/FSharpInteractivePad.fs \
	MonoDevelop.FSharpBinding/FSharpOptionsPanels.fs \
	MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs \
	MonoDevelop.FSharpBinding/FSharpResourceIdBuilder.fs \
	MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs \
	MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs \
	MonoDevelop.FSharpBinding/FSharpProjectServiceExtension.fs \
	MonoDevelop.FSharpBinding/FSharpParser.fs \
	MonoDevelop.FSharpBinding/FSharpTextEditorCompletion.fs \
	MonoDevelop.FSharpBinding/FSharpResolverProvider.fs \

REFERENCES = \
	-r:$(MONOBIN)/mscorlib.dll \
	-r:System.dll \
	-r:System.Core.dll \
	-r:System.Xml.dll \
	-r:$(MONOBIN)/Mono.Posix.dll \
	-r:$(MONOBIN)/Mono.Cairo.dll \
	-r:$(MADIR)/Mono.Addins.dll \
	-r:$(MDBIN)/MonoDevelop.Core.dll \
	-r:$(MDBIN)/MonoDevelop.Ide.dll \
	-r:$(MDADDIN)/MonoDevelop.Refactoring/MonoDevelop.Refactoring.dll \
	-r:$(MDADDIN)/BackendBindings/MonoDevelop.CSharpBinding.dll \
	-r:$(MDBIN)/Mono.TextEditor.dll \
	-r:$(MDBIN)/ICSharpCode.NRefactory.dll \
	-r:$(MDBIN)/ICSharpCode.NRefactory.CSharp.dll \
	-r:$(FSBIN)/FSharp.Core.dll \
	-r:$(FSBIN)/FSharp.Compiler.dll \
	-r:$(FSBIN)/FSharp.Compiler.Interactive.Settings.dll \
	-r:$(FSBIN)/FSharp.Compiler.Server.Shared.dll \
	-r:$(ATKDIR)/atk-sharp.dll \
	-r:$(PANGODIR)/pango-sharp.dll \
	-r:$(GTKDIR)/gtk-sharp.dll \
	-r:$(GDKDIR)/gdk-sharp.dll \
	-r:$(GLIBDIR)/glib-sharp.dll

OPTIONS = \
	--resident --noframework --debug --optimize- --target:library -r:bin/FSharpBinding.Gui.dll --out:bin/FSharpBinding.dll

# CSharp project that contains designer generated GTK stuff for project options

GUIFILES = \
	MonoDevelop.FSharpBinding/Gui/FSharpBuildOrderWidget.cs \
	MonoDevelop.FSharpBinding/Gui/FSharpSettingsWidget.cs \
	MonoDevelop.FSharpBinding/Gui/FSharpCompilerOptionsWidget.cs \
	MonoDevelop.FSharpBinding/Gui/gtk-gui/FSharp.MonoDevelop.Gui.FSharpBuildOrderWidget.cs \
	MonoDevelop.FSharpBinding/Gui/gtk-gui/FSharp.MonoDevelop.Gui.FSharpSettingsWidget.cs \
	MonoDevelop.FSharpBinding/Gui/gtk-gui/FSharp.MonoDevelop.Gui.FSharpCompilerOptionsWidget.cs \
	MonoDevelop.FSharpBinding/Gui/gtk-gui/generated.cs

GUIOPTIONS = \
	-debug+ -out:bin/FSharpBinding.Gui.dll -target:library

bin/FSharpBinding.dll: bin/FSharpBinding.Gui.dll $(FILES)
	$(FSC) $(OPTIONS) $(REFERENCES) $(RESOURCES) $(FILES) 

bin/FSharpBinding.Gui.dll: $(GUIFILES)
	mkdir -p bin
	$(CSC) $(GUIOPTIONS) $(REFERENCES) $(GUIFILES) 

install: bin/FSharpBinding.dll  bin/FSharpBinding.Gui.dll
	cp bin/FSharpBinding.* $(MDADDIN)/BackendBindings/
	gacutil /i $(FSBIN)/FSharp.Compiler.dll
	gacutil /i $(FSBIN)/FSharp.Compiler.Server.Shared.dll

uninstall:
	rm $(MDADDIN)/BackendBindings/FSharpBinding.*
	rm $(MDADDIN)/BackendBindings/FSharpCompiler.dll

package: bin/FSharpBinding.dll  bin/FSharpBinding.Gui.dll
	mkdir -p bin/repository
	mkdir -p repository
	cp bin/FSharpBinding.* bin/repository
	cp MonoDevelop.FSharpBinding/FSharpBinding.addin.xml bin/repository
	$(MDTOOL) setup pack bin/repository/FSharpBinding.addin.xml -d:repository

clean:
	rm -r bin
