# Makefile for compiling and installing F# AutoComplete engine

# Here are a few paths that need to be configured first:
MONOBIN = INSERT_MONO_BIN
FSC = mono $(MONOBIN)/fsc.exe

FILES_FCB = \
	FSharp.CompilerBinding/Common.fs \
	FSharp.CompilerBinding/CompilerLocationUtils.fs \
	FSharp.CompilerBinding/Digraph.fs \
	FSharp.CompilerBinding/OrderAssemblyReferences.fs

FILES_FAC = \
	FSharp.AutoComplete/Debug.fs \
	FSharp.AutoComplete/Options.fs \
	FSharp.AutoComplete/ProjectParser.fs \
	FSharp.AutoComplete/Parser.fs \
	FSharp.AutoComplete/TipFormatter.fs \
	FSharp.AutoComplete/Program.fs

REFERENCES = \
	-r:$(MONOBIN)/mscorlib.dll \
	-r:System.dll \
	-r:System.Core.dll \
	-r:System.Xml.dll \
	-r:Microsoft.Build.dll \
	-r:Microsoft.Build.Engine.dll \
	-r:Microsoft.Build.Framework.dll \
	-r:Microsoft.Build.Tasks.v4.0.dll \
	-r:Microsoft.Build.Utilities.v4.0.dll \
	-r:../gac//Mono.Cecil/0.9.5.0__0738eb9f132ed756/Mono.Cecil.dll \
	-r:monodevelop/MonoDevelop.FSharpBinding/packages/FSharp.Compiler.Editor.1.0.7/lib/net40/FSharp.Compiler.Editor.dll \
	-r:lib/ndesk-options/NDesk.Options.dll \
	-r:lib/newtonsoft.json/Newtonsoft.Json.dll \
	-r:$(MONOBIN)/FSharp.Core.dll 

config=Release

FSC_OPTS = --noframework --nologo

ifeq ($(config),Debug)
FSC_OPTS += --debug --optimize-
else
FSC_OPTS += --debug:pdbonly --optimize
endif

TARGETS = bin/FSharp.Core.dll bin/FSharp.CompilerBinding.dll bin/fsautocomplete.exe

all: $(TARGETS)

bin/fsautocomplete.exe: $(FILES_FAC) bin/FSharp.CompilerBinding.dll
	@-mkdir -p bin
	$(FSC) $(FSC_OPTS) --out:bin/fsautocomplete.exe -r:bin/FSharp.CompilerBinding.dll $(REFERENCES) $(FILES_FAC) 

bin/FSharp.CompilerBinding.dll: $(FILES_FCB)
	@-mkdir -p bin
	$(FSC) $(FSC_OPTS) --target:library --out:bin/FSharp.CompilerBinding.dll $(REFERENCES) $(FILES_FCB)

bin/FSharp.Core.dll: $(MONOBIN)/FSharp.Core.dll
	@-mkdir -p  bin
	cp -p $(MONOBIN)/FSharp.Core.dll bin/FSharp.Core.dll

clean:
	-rm -fr bin

autocomplete: bin/fsautocomplete.exe
