// Autogenerated from WindowsPlatform.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("MonoDevelop Windows Platform Support")]
[assembly: AssemblyCopyright ("MIT X11")]
[assembly: AssemblyVersion ("1.9.1")]
[assembly: AssemblyDescription ("Windows Platform Support for MonoDevelop")]
