
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Navigation
{
	public partial class TypeNavigationWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Navigation.TypeNavigationWindow
			this.Name = "MonoDevelop.Navigation.TypeNavigationWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TypeNavigationWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
