#if CODE_ANALYSIS_BASELINE
using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "1#", Scope = "member", Target = "Microsoft.VisualStudio.Language.Intellisense.ICompletionSource.#TryGetBestMatch(Microsoft.VisualStudio.Language.Intellisense.ICompletionSession,Microsoft.VisualStudio.Language.Intellisense.ICompletion&,Microsoft.VisualStudio.Language.Intellisense.CompletionSelectionOptions&)", Justification = "This is part of the 'TryGet' pattern.  This needs to be an out parameter.")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "1#", Scope = "member", Target = "Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSource.#GetToolTipContent(Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSession,Microsoft.VisualStudio.Text.ITrackingSpan&)", Justification = "Considered, and rejected.  We need ApplicableToSpan to be an out parameter.")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.IParameter.#GetParameterLocusInUnderlyingBuffer()", MessageId="", Justification="BASELINE: This is a method because it does work and its value changes all the time.")]
[module: SuppressMessage("Microsoft.Design","CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.CompletionSet.#GetBestMatch()", Justification="Definitely a method")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.StandardGlyphGroup.#GlyphBscFile", MessageId="Bsc", Justification="BASELINE: Ignore naming of code types")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.StandardGlyphGroup.#GlyphCppProject", MessageId="Cpp", Justification="BASELINE: Ignore naming of code types")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.StandardGlyphGroup.#GlyphGroupTypedef", MessageId="Typedef", Justification="BASELINE: Ignore naming of code types")]
[module: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope="type", Target="Microsoft.VisualStudio.Language.Intellisense.IIntellisenseSessionStack", MessageId="", Justification="BASELINE: Ingore this naming violation.  We want to name this 'Stack'")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Add(!0)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Add(System.Object)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Clear()", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Insert(System.Int32,!0)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Insert(System.Int32,System.Object)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Remove(!0)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#Remove(System.Object)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#RemoveAt(System.Int32)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#set_Item(System.Int32,!0)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="FilteredObservableCollections", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#System.Collections.IList.set_Item(System.Int32,System.Object)", Justification="Class Name")]
[module: SuppressMessage("Microsoft.Usage","CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.CompletionSet.#CompletionBuilders", Justification="Settable in order to allow derived classes the freedom of implementing their own")]
[module: SuppressMessage("Microsoft.Usage","CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.CompletionSet.#Completions", Justification="Settable in order to allow derived classes the freedom of implementing their own")]

//ToDo: To be looked at
[module: SuppressMessage("Microsoft.Design","CA1021:AvoidOutParameters", MessageId="2#", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSource.#AugmentQuickInfoSession(Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSession,System.Collections.Generic.IList`1<System.Object>,Microsoft.VisualStudio.Text.ITrackingSpan&)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Usage","CA2214:DoNotCallOverridableMethodsInConstructors", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.CompletionSet.#.ctor(System.String,System.String,Microsoft.VisualStudio.Text.ITrackingSpan,System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Language.Intellisense.Completion>,System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Language.Intellisense.Completion>)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.CompletionSet.#MatchCompletionList(System.Collections.Generic.IList`1<Microsoft.VisualStudio.Language.Intellisense.Completion>,Microsoft.VisualStudio.Language.Intellisense.CompletionMatchType,System.Boolean)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Language.Intellisense.FilteredObservableCollection`1.#CopyTo(System.Array,System.Int32)", Justification="ToDo: To be looked at")]

#endif
