// Autogenerated from MonoDevelop.Ide.addin.xml

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("MonoDevelop Ide")]
[assembly: AssemblyDescription ("The MonoDevelop IDE application.")]
[assembly: AssemblyVersion ("2.6")]
[assembly: AssemblyCopyright ("LGPL")]

[assembly: InternalsVisibleTo("MacPlatform")]
[assembly: InternalsVisibleTo("MonoDevelop.Debugger")]
[assembly: InternalsVisibleTo("MonoDevelop.DesignerSupport")]
