// Autogenerated from MonoDevelop.Ide.addin.xml

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("MonoDevelop Ide")]
[assembly: AssemblyDescription ("The MonoDevelop IDE application.")]
[assembly: AssemblyVersion ("2.6")]
[assembly: AssemblyCopyright ("LGPL")]

[assembly: InternalsVisibleTo("MacPlatform")]
[assembly: InternalsVisibleTo("WindowsPlatform")]
[assembly: InternalsVisibleTo("MonoDevelop.Debugger")]
[assembly: InternalsVisibleTo("MonoDevelop.DesignerSupport")]
[assembly: InternalsVisibleTo("Ide.Tests")]
[assembly: InternalsVisibleTo("UnitTests")]
[assembly: InternalsVisibleTo("MonoDevelop.Refactoring")]
[assembly: InternalsVisibleTo("Xamarin.Ide")]
[assembly: InternalsVisibleTo("MonoDevelop.SourceEditor")]
[assembly: InternalsVisibleTo("MonoDevelop.SourceEditor2")]
