#!/bin/bash

pushd `dirname $0` > /dev/null
export HOME=`pwd`
popd > /dev/null
emacs -batch -l test-utilities.el -l pos-tip-mock.el -l basic-tests.el -l intellisense-tests.el -l unit-tests.el -f ert-run-tests-batch-and-exit
