
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.AddinAuthoring
{
	public partial class ExtensionEditorWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button buttonAdd;

		private global::Gtk.Button addNodeButton;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image image445;

		private global::Gtk.Label label1;

		private global::Gtk.Arrow arrow1;

		private global::Gtk.Button buttonRemove;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow scrolledwindow6;

		private global::Gtk.TreeView tree;

		private global::Gtk.ScrolledWindow editorBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.AddinAuthoring.ExtensionEditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.AddinAuthoring.ExtensionEditorWidget";
			// Container child MonoDevelop.AddinAuthoring.ExtensionEditorWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonAdd = new global::Gtk.Button ();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child buttonAdd.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "md-extension-point", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Select Extension Points");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.buttonAdd.Add (w1);
			this.hbox1.Add (this.buttonAdd);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonAdd]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.addNodeButton = new global::Gtk.Button ();
			this.addNodeButton.CanFocus = true;
			this.addNodeButton.Name = "addNodeButton";
			this.addNodeButton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child addNodeButton.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image445 = new global::Gtk.Image ();
			this.image445.Name = "image445";
			this.image445.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.hbox2.Add (this.image445);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image445]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Add Node");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.arrow1 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(1)), ((global::Gtk.ShadowType)(2)));
			this.arrow1.Name = "arrow1";
			this.hbox2.Add (this.arrow1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.arrow1]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.addNodeButton.Add (this.hbox2);
			this.addNodeButton.Label = null;
			this.hbox1.Add (this.addNodeButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.addNodeButton]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonRemove = new global::Gtk.Button ();
			this.buttonRemove.CanFocus = true;
			this.buttonRemove.Name = "buttonRemove";
			this.buttonRemove.UseUnderline = true;
			this.buttonRemove.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child buttonRemove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Remove");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.buttonRemove.Add (w15);
			this.hbox1.Add (this.buttonRemove);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonRemove]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 411;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow6 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow6.CanFocus = true;
			this.scrolledwindow6.Name = "scrolledwindow6";
			this.scrolledwindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow6.Gtk.Container+ContainerChild
			this.tree = new global::Gtk.TreeView ();
			this.tree.CanFocus = true;
			this.tree.Name = "tree";
			this.scrolledwindow6.Add (this.tree);
			this.hpaned1.Add (this.scrolledwindow6);
			global::Gtk.Paned.PanedChild w26 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.scrolledwindow6]));
			w26.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.editorBox = new global::Gtk.ScrolledWindow ();
			this.editorBox.CanFocus = true;
			this.editorBox.Name = "editorBox";
			this.editorBox.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.hpaned1.Add (this.editorBox);
			this.hbox4.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hpaned1]));
			w28.Position = 0;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w29.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
			this.addNodeButton.Pressed += new global::System.EventHandler (this.OnAddNodeButtonPressed);
			this.buttonRemove.Clicked += new global::System.EventHandler (this.OnButtonRemoveClicked);
			this.tree.PopupMenu += new global::Gtk.PopupMenuHandler (this.OnTreePopupMenu);
			this.tree.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnTreeButtonReleaseEvent);
		}
	}
}
