// Autogenerated from JavaBinding.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("Java Language Binding")]
[assembly: AssemblyDescription ("Java Language Binding")]
[assembly: AssemblyVersion ("2.2")]
[assembly: AssemblyCopyright ("GPL")]
