// Autogenerated from CSharpBinding.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("CSharp Language Binding")]
[assembly: AssemblyCopyright ("GPL")]
[assembly: AssemblyVersion ("1.9.1")]
[assembly: AssemblyDescription ("CSharp Language Binding")]
