.TH "monodevelop" 1
.SH NAME
monodevelop \- Free GNOME Development Environment
.SH SYNOPSIS
.B monodevelop
[options] [projectfile]
.SH DESCRIPTION
.B monodevelop
Free GNOME Development Environment
.SH Options
.PP
.TP
.B --debug
Run mono in debug mode
.TP
.B --trace
Run mono in trace mode
.TP
.B --profile
Run mono in profile mode
.TP
.B --new-window
force MD to open a new instance instead of passing to a running one. This option is forced if opening a combine.
.SH ENVIRONMENT VARIABLES
.PP
.TP
.B MONODEVELOP_CONSOLE_LOG_LEVEL
The logging level, possible values are `fatal', `error', `warn', `info' and `debug'. The default is to log fatal, error and warn.
.TP
.B MONODEVELOP_CONSOLE_LOG_USE_COLOUR
Use colour in log - true or false. The default is false.
.TP
.B MONODEVELOP_LOG_FILE
If set, log is written to the specified file.
.TP
.B MONODEVELOP_FILE_LOG_LEVEL
The logging level, possible values are `fatal', `error', `warn', `info' and `debug'. Valid only if MONODEVELOP_LOG_FILE is specified. The default is to log fata, error, warn and info.

.SH SEE ALSO
mdtool(1), mono(1), mcs(1)
.BR
.SH COPYRIGHT
Copyright (C) 2008 Novell, Inc (http://www.novell.com)
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/monodevelop-list for details.
.SH WEB SITE
Visit http://www.monodevelop.com for details
