#if CODE_ANALYSIS_BASELINE
using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Scope="", Target="microsoft.visualstudio.logic.text.classification.aggregator.implementation.dll", MessageId="", Justification="BASELINE: Original port of VisualStudio to ToolPlat")]
[module: SuppressMessage("Microsoft.Reliability","CA2000:Dispose objects before losing scope", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.#CreateTagger`1(Microsoft.VisualStudio.Text.ITextBuffer)", Justification="Factory")]
[module: SuppressMessage("Microsoft.Reliability","CA2000:Dispose objects before losing scope", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregatorService.#GetClassifier(Microsoft.VisualStudio.Text.ITextBuffer)", Justification="Factory")]
[module: SuppressMessage("Microsoft.Reliability","CA2000:Dispose objects before losing scope", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregatorService.#GetClassifier(Microsoft.VisualStudio.Text.Editor.ITextView)", Justification="Factory")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="EndBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMap.#EndBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="BeginBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMap.#EndBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="EndBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMap.#BeginBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="BeginBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMap.#BeginBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="EndBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMap.#EndBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="BeginBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMap.#EndBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="EndBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMap.#BeginBatchUpdate()", Justification="Valid member name")]
[module: SuppressMessage("Microsoft.Naming","CA2204:Literals should be spelled correctly", MessageId="BeginBatchUpdate", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMap.#BeginBatchUpdate()", Justification="Valid member name")]

//ToDo: To be looked at
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMapService.#GetClassificationFormatMap(Microsoft.VisualStudio.Text.Editor.ITextView)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Design","CA1062:Validate arguments of public methods", MessageId="0", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMapService.#GetEditorFormatMap(Microsoft.VisualStudio.Text.Editor.ITextView)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ProjectionWorkaroundProvider.#set_diffService(Microsoft.VisualStudio.Text.Differencing.IDifferenceService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMapService.#set__formats(System.Collections.Generic.List`1<System.Lazy`2<Microsoft.VisualStudio.Text.Classification.EditorFormatDefinition,Microsoft.VisualStudio.Text.Classification.IEditorFormatMetadata>>)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMapService.#set__dataStorageService(Microsoft.VisualStudio.Text.Storage.IDataStorageService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.EditorFormatMapService.#set__classificationFormatMapService(Microsoft.VisualStudio.Text.Classification.IClassificationFormatMapService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.#set__guardedOperations(Microsoft.VisualStudio.Text.Utilities.GuardedOperations)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.#set__classifierProviders(System.Collections.Generic.List`1<System.Lazy`2<Microsoft.VisualStudio.Text.Classification.IClassifierProvider,Microsoft.VisualStudio.Text.Utilities.IContentTypeMetadata>>)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregatorService.#set__viewTagAggregatorFactory(Microsoft.VisualStudio.Text.Tagging.IViewTagAggregatorFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregatorService.#set__classificationTypeRegistry(Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregatorService.#set__bufferTagAggregatorFactory(Microsoft.VisualStudio.Text.Tagging.IBufferTagAggregatorFactoryService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationTypeRegistryService.#set__classificationTypeDefinitions(System.Collections.Generic.List`1<System.Lazy`2<Microsoft.VisualStudio.Text.Classification.ClassificationTypeDefinition,Microsoft.VisualStudio.Text.Classification.Implementation.IClassificationTypeDefinitionMetadata>>)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMapService.#set__formats(System.Collections.Generic.List`1<System.Lazy`2<Microsoft.VisualStudio.Text.Classification.EditorFormatDefinition,Microsoft.VisualStudio.Text.Classification.IClassificationFormatMetadata>>)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMapService.#set__editorFormatMapService(Microsoft.VisualStudio.Text.Classification.IEditorFormatMapService)", Justification="ToDo: To be looked at")]
[module: SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMapService.#set__classificationTypeRegistry(Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService)", Justification="ToDo: To be looked at")]

#endif
