
// This file has been generated by the GUI designer. Do not modify.
namespace GitHub.Repository.UserInterface
{
	internal partial class GitHubPropertyDialog
	{
		private global::Gtk.ScrolledWindow GitHubGtkScrolledWindowForProperties;
		
		private global::MonoDevelop.Components.PropertyGrid.PropertyGrid gitHubPropertyGrid;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GitHub.Repository.UserInterface.GitHubPropertyDialog
			this.Name = "GitHub.Repository.UserInterface.GitHubPropertyDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("GitHub Properties");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child GitHub.Repository.UserInterface.GitHubPropertyDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "gitHubVirtualBoxForProperties";
			w1.BorderWidth = ((uint)(2));
			// Container child gitHubVirtualBoxForProperties.Gtk.Box+BoxChild
			this.GitHubGtkScrolledWindowForProperties = new global::Gtk.ScrolledWindow ();
			this.GitHubGtkScrolledWindowForProperties.Name = "GitHubGtkScrolledWindowForProperties";
			this.GitHubGtkScrolledWindowForProperties.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GitHubGtkScrolledWindowForProperties.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.gitHubPropertyGrid = new global::MonoDevelop.Components.PropertyGrid.PropertyGrid ();
			this.gitHubPropertyGrid.Name = "gitHubPropertyGrid";
			this.gitHubPropertyGrid.ShowToolbar = true;
			this.gitHubPropertyGrid.ShowHelp = false;
			w2.Add (this.gitHubPropertyGrid);
			this.GitHubGtkScrolledWindowForProperties.Add (w2);
			w1.Add (this.GitHubGtkScrolledWindowForProperties);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.GitHubGtkScrolledWindowForProperties]));
			w5.Position = 0;
			// Internal child GitHub.Repository.UserInterface.GitHubPropertyDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 815;
			this.DefaultHeight = 442;
			this.Show ();
		}
	}
}
