// Autogenerated from MonoDevelop.Database.Sql.Firebird.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("Firebird provider for Mono Data Sql")]
[assembly: AssemblyCopyright ("MIT X11")]
[assembly: AssemblyVersion ("1.9.1")]
[assembly: AssemblyDescription ("Database Module")]
