// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.Ide.CodeFormatting {
    
    
    public partial class CodeFormattingPolicyPanelWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeviewCategories;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label3;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.CheckButton checkbuttonWhiteSpaces;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.Ide.CodeFormatting.CodeFormattingPolicyPanelWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.Ide.CodeFormatting.CodeFormattingPolicyPanelWidget";
            // Container child MonoDevelop.Ide.CodeFormatting.CodeFormattingPolicyPanelWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 264;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeviewCategories = new Gtk.TreeView();
            this.treeviewCategories.CanFocus = true;
            this.treeviewCategories.Name = "treeviewCategories";
            this.GtkScrolledWindow.Add(this.treeviewCategories);
            this.vbox3.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
            w2.Position = 0;
            this.hpaned1.Add(this.vbox3);
            Gtk.Paned.PanedChild w3 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox3]));
            w3.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Preview:");
            this.hbox2.Add(this.label3);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label3]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            this.hbox2.Add(this.fixed1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.fixed1]));
            w5.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.checkbuttonWhiteSpaces = new Gtk.CheckButton();
            this.checkbuttonWhiteSpaces.CanFocus = true;
            this.checkbuttonWhiteSpaces.Name = "checkbuttonWhiteSpaces";
            this.checkbuttonWhiteSpaces.Label = Mono.Unix.Catalog.GetString("S_how whitespaces");
            this.checkbuttonWhiteSpaces.DrawIndicator = true;
            this.checkbuttonWhiteSpaces.UseUnderline = true;
            this.hbox2.Add(this.checkbuttonWhiteSpaces);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.checkbuttonWhiteSpaces]));
            w6.Position = 2;
            w6.Expand = false;
            this.vbox4.Add(this.hbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox4.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox4[this.scrolledwindow2]));
            w8.Position = 1;
            this.hpaned1.Add(this.vbox4);
            this.vbox2.Add(this.hpaned1);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.hpaned1]));
            w10.Position = 0;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
