// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.Projects.Gui.Dialogs.OptionPanels {
    
    
    internal partial class CompileFileOptionsWidget {
        
        private Gtk.VBox vbox48;
        
        private Gtk.Label includeLabel;
        
        private Gtk.ScrolledWindow scrolledwindow6;
        
        private Gtk.TreeView includeTreeView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.Projects.Gui.Dialogs.OptionPanels.CompileFileOptionsWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.Projects.Gui.Dialogs.OptionPanels.CompileFileOptionsWidget";
            // Container child MonoDevelop.Projects.Gui.Dialogs.OptionPanels.CompileFileOptionsWidget.Gtk.Container+ContainerChild
            this.vbox48 = new Gtk.VBox();
            this.vbox48.Name = "vbox48";
            this.vbox48.Spacing = 6;
            // Container child vbox48.Gtk.Box+BoxChild
            this.includeLabel = new Gtk.Label();
            this.includeLabel.Name = "includeLabel";
            this.includeLabel.Xalign = 0F;
            this.includeLabel.LabelProp = MonoDevelop.Core.GettextCatalog.GetString("_Include files in compile run");
            this.includeLabel.UseUnderline = true;
            this.vbox48.Add(this.includeLabel);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox48[this.includeLabel]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox48.Gtk.Box+BoxChild
            this.scrolledwindow6 = new Gtk.ScrolledWindow();
            this.scrolledwindow6.Name = "scrolledwindow6";
            this.scrolledwindow6.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow6.Gtk.Container+ContainerChild
            this.includeTreeView = new Gtk.TreeView();
            this.includeTreeView.WidthRequest = 300;
            this.includeTreeView.HeightRequest = 200;
            this.includeTreeView.Name = "includeTreeView";
            this.includeTreeView.HeadersVisible = false;
            this.includeTreeView.HeadersClickable = true;
            this.scrolledwindow6.Add(this.includeTreeView);
            this.vbox48.Add(this.scrolledwindow6);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox48[this.scrolledwindow6]));
            w3.Position = 1;
            this.Add(this.vbox48);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
