// Autogenerated from CBinding.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("C/C++ Language Binding")]
[assembly: AssemblyDescription ("C/C++ Language binding")]
[assembly: AssemblyVersion ("2.1.0")]
[assembly: AssemblyCopyright ("MIT X11")]
