#!/bin/bash

usage ()
{
	echo ""
	echo "Usage : mdtag branchVersionNumber tagVersionNumber"
	echo ""
	echo "Creates a new tag of MonoDevelop using the provided branch number as source."
	echo ""
}

if [ x$1 = x ]; then
	usage
	exit 1
fi

if [ x$2 = x ]; then
	echo "Branch version number not provided"
	exit 1
fi

./mdbranch --tag $1 $2

