# Makefile for compiling, installing and packing F# MonoDevelop plugin on Mono
#
#   run 'make' to compile the plugin against the installed version of MonoDevelop detected by ./configure.sh
#   run 'make install' to compile and install the plugin against the installed version of MonoDevelop detected by ./configure.sh
#   run 'make pack-all' to create a deployment binary packages for the known set of supported MonoDevelop versions

VERSION=INSERT_VERSION

MDTOOL = mono 'INSERT_MDROOT/bin/mdtool.exe'

# (MDVERSION4) can be set to something like (3.0.4, 3.0.4.7) to compile
# against the dependencies/... binaries for a specific version of MonoDevelop. This allows
# us to prepare new editions of the binding for several different versions of MonoDevelop.
MDVERSION4=INSERT_MDVERSION4

ifeq ($(USE_KNOWN_BINARIES),true)
MDROOT=../dependencies/monodevelop.$(MDVERSION4)
MDTAG=monodevelop-$(MDVERSION4)
else
MDROOT=INSERT_MDROOT
MDTAG=mac-linux
endif


# The default configuration is Debug
ifeq ($(config),)
config=Debug
endif

.PHONY: all

all: build

build: MonoDevelop.FSharpBinding/MonoDevelop.FSharp.$(MDTAG).fsproj MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
	(cd MonoDevelop.FSharpBinding && xbuild MonoDevelop.FSharp.$(MDTAG).fsproj /p:Configuration=$(config))

pack: build
	-rm -fr pack/$(VERSION)/$(MDTAG)/$(config)
	@-mkdir -p pack/$(VERSION)/$(MDTAG)/$(config)
	$(MDTOOL) setup pack bin/$(MDTAG)/$(config)/FSharpBinding.dll -d:pack/$(VERSION)/$(MDTAG)/$(config)

install: pack
	$(MDTOOL) setup install -y pack/$(VERSION)/$(MDTAG)/$(config)/MonoDevelop.FSharpBinding_$(VERSION).mpack 

uninstall:
	$(MDTOOL) setup uninstall MonoDevelop.FSharpBinding

release: 
	$(MAKE) config=Release pack

clean:
	-rm -fr bin
	-rm -fr pack
	-rm -fr MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
	-rm -fr MonoDevelop.FSharpBinding/MonoDevelop.FSharp.*.fsproj
	-rm -fr MonoDevelop.FSharpBinding/obj
	(cd MonoDevelop.FSharpBinding/Gui && xbuild MonoDevelop.FSharp.Gui.csproj /target:Clean)

