// Autogenerated from MonoDevelop.Refactoring.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("Refactoring Support")]
[assembly: AssemblyDescription ("Provides refactoring support to MonoDevelop")]
[assembly: AssemblyVersion ("2.1.1")]
[assembly: AssemblyCopyright ("X11")]
