
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NUnit
{
	internal partial class NUnitOptionsWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.CheckButton useParentCheck;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.RadioButton noFilterRadio;
		private global::Gtk.RadioButton includeRadio;
		private global::Gtk.RadioButton excludeRadio;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label4;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TreeView categoryTree;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button addButton;
		private global::Gtk.Button removeButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NUnit.NUnitOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.NUnit.NUnitOptionsWidget";
			// Container child MonoDevelop.NUnit.NUnitOptionsWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.useParentCheck = new global::Gtk.CheckButton ();
			this.useParentCheck.Name = "useParentCheck";
			this.useParentCheck.Label = global::Mono.Unix.Catalog.GetString ("Use parent test settings");
			this.useParentCheck.DrawIndicator = true;
			this.useParentCheck.UseUnderline = true;
			this.vbox1.Add (this.useParentCheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.useParentCheck]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("The following filter will be applied when running the tests:");
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 18;
			this.label2.Name = "label2";
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.noFilterRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Don't apply any filter"));
			this.noFilterRadio.Name = "noFilterRadio";
			this.noFilterRadio.Active = true;
			this.noFilterRadio.DrawIndicator = true;
			this.noFilterRadio.UseUnderline = true;
			this.noFilterRadio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox4.Add (this.noFilterRadio);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.noFilterRadio]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.includeRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Include the following categories"));
			this.includeRadio.Name = "includeRadio";
			this.includeRadio.DrawIndicator = true;
			this.includeRadio.UseUnderline = true;
			this.includeRadio.Group = this.noFilterRadio.Group;
			this.vbox4.Add (this.includeRadio);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.includeRadio]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.excludeRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Exclude the following categories"));
			this.excludeRadio.Name = "excludeRadio";
			this.excludeRadio.DrawIndicator = true;
			this.excludeRadio.UseUnderline = true;
			this.excludeRadio.Group = this.noFilterRadio.Group;
			this.vbox4.Add (this.excludeRadio);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.excludeRadio]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w9.Position = 1;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Categories:");
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 18;
			this.label4.Name = "label4";
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.categoryTree = new global::Gtk.TreeView ();
			this.categoryTree.Name = "categoryTree";
			this.scrolledwindow1.Add (this.categoryTree);
			this.hbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.scrolledwindow1]));
			w14.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.addButton = new global::Gtk.Button ();
			this.addButton.Name = "addButton";
			this.addButton.UseStock = true;
			this.addButton.UseUnderline = true;
			this.addButton.Label = "gtk-add";
			this.vbox2.Add (this.addButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.addButton]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.removeButton = new global::Gtk.Button ();
			this.removeButton.Name = "removeButton";
			this.removeButton.UseStock = true;
			this.removeButton.UseUnderline = true;
			this.removeButton.Label = "gtk-remove";
			this.vbox2.Add (this.removeButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.removeButton]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w18.Position = 4;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
